version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    command: --secure-file-priv=/var/lib/mysql-files
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./titanic.csv:/var/lib/mysql-files/titanic.csv